### ISSUE TITLE
Resource Gathering AI Improvements

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#216]
- [ ] Add idle position-differential thinker while not actively chopping wood, to determine that the builder has stopped while trying to reach a tree and should try to move around choosing another close to it
- [ ] Add more data to trees, such as the list of builders currently working on it (instead of a single one) and access level (an unreachable tree has 0 while a solitary tree has 8 or even more peons that could work on it)
- [x] Make a "Tree Island" system that keeps references to trees in certain zone, to improve the efficiency of decisions and tree finding
- [ ] Ordering multiple gatherers to grab from a tree:
  - [ ] should always go towards that island
  - [ ] assign more than one builder to each tree when there aren't enough reachable trees to gather from
- [ ] Try to make these scripts library-able
  - [ ] order filtering should be transparent
  - [x] provide a settings file
- [x] `DeterminePathableTrees` should save to file per map while IsInToolsMode(), load to save processing

**Comment by MNoya** [comment]
- [ ] Gather sometimes not continuing, stuck modifier/can't return 0.
- [ ] Peasant idle counter incorrect while transitioning from moving to gather
- [ ] Wisps got order stuck going to gold mine
