### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#300]
**Core Gameplay**
- [x] Finish neutral features #94
- [x] Finish [Parity milestone](https://github.com/MNoya/DotaCraft/milestone/5)
- [ ] Finish gathering mechanics #216
- [ ] Refactor altar scripts #183
- [ ] Make win condition more stable #185
- [ ] Change precache systems #225 #293 
- [ ] Add 7+ ability building layouts/building extended bar #88
- [ ] Update building visuals #221 #224 #265 #266 #283 #288 #295
- [ ] Replace all remaining wc3 icons

**Test and Polish** @http://bit.ly/DotaCraft-Sheet
- [x] Hero abilities
- [x] Unit abilities
- [x] Items
- [ ] UI elements
- [ ] Mapping

**Extra Features**
AI, Tutorial, Stats, Web, Wiki, Ladder
